package com.example.demo.domain;

import javax.persistence.*;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;;

import lombok.Data;

@Data
@JsonInclude(Include.NON_DEFAULT)
@Entity
@Table(name = "AdminDetails")
public class AdminDetails {
    @Id
    @Column(name = "UserID")
    private String userID;
    
    @Column(name = "Password")
    private String password;
    
    // Constructors, getters, and setters to be generated by lombok
}
